cache:
  paths:
    - cache/

stages:
  - test

test:
  stage: test
  before_script:
    - apt-get install apt-transport-https
    - apt-get update -qq && apt-get -qq install -y php5 php5-cli php5-gd php5-mysql
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer install
    - ./vendor/phpunit/phpunit/phpunit -c -v Configuration/Build/UnitTests.xml
