cache:
  key: "$CI_BUILD_REF_NAME/$CI_BUILD_STAGE"
  paths:
    - .composer/

stages:
  - test
  - upload

.test: &testing
  stage: test
  image: php:$DOCKER_TAG
  only:
    - branches
  before_script:
    - curl -OL https://github.com/squizlabs/PHP_CodeSniffer/releases/download/2.8.0/phpcs.phar
    - apk --update add wget curl git && rm /var/cache/apk/*
    - "[ -d .Build/bin ] || mkdir -p .Build/bin"
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=.Build/bin/ --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - php .Build/bin/composer require typo3/cms="${TYPO3_VERSION}" --prefer-source --update-with-dependencies
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c Configuration/.Build/Tests/$UNIT_TEST_CONFIG_FILENAME
    - php phpcs.phar --standard=PSR2 --config-set warning_severity 8 Classes Configuration/TCA Tests/Unit


# Tests in PHP 5.6 and TYPO3 6.2
test:php56:typo3_62:
  <<: *testing
  variables:
    DOCKER_TAG: 5.6-alpine
    TYPO3_VERSION: ^6.2
    UNIT_TEST_CONFIG_FILENAME: UnitTests.xml

# Build in PHP 5.6 and TYPO3 7.6
test:php56:typo3_7:
  <<: *testing
  variables:
    DOCKER_TAG: 5.6-alpine
    TYPO3_VERSION: ^7.6
    UNIT_TEST_CONFIG_FILENAME: UnitTests.xml

# Build in PHP 7.0 and TYPO3 7.6
test:php70:typo3_7:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: ^7.6
    UNIT_TEST_CONFIG_FILENAME: UnitTests.xml

# Build in PHP 7.1 and TYPO3 7.6
test:php71:typo3_7:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: ^7.6
    UNIT_TEST_CONFIG_FILENAME: UnitTests.xml

# Build in PHP 7.0 and TYPO3 8 (latest stable release)
test:php70:typo3_8:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: ^8
    UNIT_TEST_CONFIG_FILENAME: UnitTests-8.xml

# Build in PHP 7.1 and TYPO3 8 (latest stable release)
test:php71:typo3_8:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: ^8
    UNIT_TEST_CONFIG_FILENAME: UnitTests-8.xml

# Build in PHP 7.0 and TYPO3 (current master)
test:php70:typo3_master:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: dev-master
    UNIT_TEST_CONFIG_FILENAME: UnitTests-8.xml

# Build in PHP 7.1 and TYPO3 (current master)
test:php71:typo3_master:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: dev-master
    UNIT_TEST_CONFIG_FILENAME: UnitTests-8.xml

# TER Upload when tagging in master branch
# The variables T3O_USERNAME and T3O_PASSWORD should be set in GitLab
ter-upload:
  stage: upload
  only:
    - tags
    - master
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer install
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - >
      if [ -n "$CI_BUILD_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_BUILD_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_BUILD_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_BUILD_TAG} to TER"
        .Build/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;
