.job_template: &unit_test  # Hidden key that defines an anchor named 'job_definition'
  image: webdevops/php:$DOCKER_TAG
  only:
    - branches
  except:
    - master
  stage: test
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer require typo3/cms="${TYPO3_VERSION}"
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml

cache:
  paths:
    - cache/

stages:
  - test
  - deploy

unittest-php56-62:
  <<: *unit_test
  variables:
    DOCKER_TAG: debian-8
    TYPO3_VERSION: ^6.2

unittest-php56-7:
  <<: *unit_test
  variables:
    DOCKER_TAG: debian-8
    TYPO3_VERSION: ^7.6

unittest-php7-7:
  <<: *unit_test
  variables:
    DOCKER_TAG: debian-9
    TYPO3_VERSION: ^7.6

unittest-php7-8:
  <<: *unit_test
  variables:
    DOCKER_TAG: debian-9
    TYPO3_VERSION: ^8

unittest-php7-master:
  <<: *unit_test
  variables:
    DOCKER_TAG: debian-9
    TYPO3_VERSION: dev-master

ter-upload:
  only:
    - tags
    - master
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer install
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - >
      if [ -n "$CI_BUILD_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_BUILD_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_BUILD_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_BUILD_TAG} to TER"
        .Build/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;