before_script:
  - apt-get update && apt-get -y install phpunit
  - composer install

stages:
  - test

test:
  script:
  - phpunit -c htdocs/typo3conf/ext/be_secure_pw/Configuration/Build/UnitTests.xml