# Template for Build for better reuse
.job_template: &building
  image: php:7.1-alpine
  only:
    - branches
  except:
    - master
  stage: build
  before_script:
    - mkdir .Build/bin
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=.Build/bin/ --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - php .Build/bin/composer install
  artifacts:
    name: "$CI_BUILD_NAME"
    when: on_success
    expire_in: 1 hour
    paths:
      - .Build

.job_template: &testing
  image: php:$DOCKER_TAG
  only:
    - branches
  except:
    - master
  stage: test
  script:
    - php .Build/bin/composer require typo3/cms="${TYPO3_VERSION}"
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml


cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - cache/

stages:
  - build
  - test
  - upload

buildComposer:
  <<: *building

# Build in PHP 5.6 and TYPO3 6.2
php56-typo3-62:
  <<: *testing
  variables:
    DOCKER_TAG: 5.6-alpine
    TYPO3_VERSION: ^6.2

# Build in PHP 5.6 and TYPO3 7.6
php56-typo3-7:
  <<: *testing
  variables:
    DOCKER_TAG: 5.6-alpine
    TYPO3_VERSION: ^7.6

# Build in PHP 7.0 and TYPO3 7.6
php7.0-typo3-7:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: ^7.6

# Build in PHP 7.1 and TYPO3 7.6
php7.1-typo3-7:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: ^7.6

# Build in PHP 7.0 and TYPO3 8 (latest stable release)
php7.0-typo3-8:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: ^8

# Build in PHP 7.1 and TYPO3 8 (latest stable release)
php7.1-typo3-8:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: ^8

# Build in PHP 7.0 and TYPO3 (current master)
php7.0-typo3-master:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: dev-master

# Build in PHP 7.1 and TYPO3 (current master)
php7.1-typo3-master:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: dev-master

# TER Upload when tagging in master branch
# The variables T3O_USERNAME and T3O_PASSWORD should be set in GitLab
ter-upload:
  stage: upload
  only:
    - tags
    - master
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer install
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - >
      if [ -n "$CI_BUILD_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_BUILD_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_BUILD_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_BUILD_TAG} to TER"
        .Build/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;