cache:
  paths:
    - cache/

stages:
  - test
  - deploy

unittest-php56-62:
  image: webdevops/php:debian-8
  only:
    - branches
  except:
    - master
  stage: test
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer require typo3/cms="^6.2"
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml

unittest-php56-7:
  image: webdevops/php:debian-8
  only:
    - branches
  except:
    - master
  stage: test
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer require typo3/cms="^7.6"
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml

unittest-php7-7:
  image: webdevops/php:debian-9
  only:
    - branches
  except:
    - master
  stage: test
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer require typo3/cms="^7.6"
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml

unittest-php7-8:
  image: webdevops/php:debian-9
  only:
    - branches
  except:
    - master
  stage: test
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer require typo3/cms="^8"
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml

unittest-php7-master:
  image: webdevops/php:debian-9
  only:
    - branches
  except:
    - master
  stage: test
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer require typo3/cms="dev-master"
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml

ter-upload:
  only:
    - tags
    - master
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=/cache/composer
  script:
    - composer install
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - >
      if [ -n "$CI_BUILD_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_BUILD_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Build extension files
        composer extension-release
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_BUILD_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_BUILD_TAG} to TER"
        .Build/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;