cache:
  key: "$CI_COMMIT_REF_NAME/$CI_JOB_STAGE"
  paths:
    - .cache/

before_script:
  - apk add git --update

stages:
  - test
  - mirror
  - release

.test: &testing
  stage: test
  image: php:$DOCKER_TAG
  only:
    - branches
  before_script:
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - export COMPOSER_CACHE_DIR=.cache/composer
    - php -r "copy('https://getcomposer.org/composer.phar', 'composer.phar');"
    - echo $COMPOSER_STABILITY
    - php composer.phar config minimum-stability $COMPOSER_STABILITY
    - php composer.phar config --list
    - php composer.phar require typo3/cms="${TYPO3_VERSION}" --update-with-dependencies
    - php composer.phar require nimut/testing-framework
    - php composer.phar require squizlabs/php_codesniffer
  script:
    - .Build/bin/phpunit -c Configuration/.Build/Tests/UnitTests.xml
    - .Build/bin/phpcs --standard=PSR2 --extensions=php *

# Build in PHP 7.0 and TYPO3 7.6
test:php70:typo3_7:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: ^7.6
    COMPOSER_STABILITY: stable

# Build in PHP 7.1 and TYPO3 7.6
test:php71:typo3_7:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: ^7.6
    COMPOSER_STABILITY: stable

# Build in PHP 7.0 and TYPO3 8 (latest stable release)
test:php70:typo3_8:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: ^8
    COMPOSER_STABILITY: stable

# Build in PHP 7.1 and TYPO3 8 (latest stable release)
test:php71:typo3_8:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: ^8
    COMPOSER_STABILITY: stable

# Build in PHP 7.0 and TYPO3 (current master)
test:php70:typo3_master:
  <<: *testing
  variables:
    DOCKER_TAG: 7.0-alpine
    TYPO3_VERSION: dev-master
    COMPOSER_STABILITY: dev

# Build in PHP 7.1 and TYPO3 (current master)
test:php71:typo3_master:
  <<: *testing
  variables:
    DOCKER_TAG: 7.1-alpine
    TYPO3_VERSION: dev-master
    COMPOSER_STABILITY: dev

mirror-to-github:
  stage: mirror
  image: indiehosters/git
  only:
    - master
  script:
    - git remote add github https://tomalo:$GITHUB_TOKEN@github.com/spoonerWeb/be_secure_pw.git
    - git push github master
    - git push github master --tags

# TER Upload when tagging in master branch
# The variables T3O_USERNAME and T3O_PASSWORD should be set in GitLab
ter-upload:
  image: webdevops/php
  stage: release
  only:
    - tags
  before_script:
    - php -r "copy('https://getcomposer.org/composer.phar', 'composer.phar');"
    - export COMPOSER_CACHE_DIR=.cache/composer
  script:
    - php composer.phar require namelesscoder/typo3-repository-client
    - >
      if [ -n "$CI_COMMIT_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_COMMIT_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_COMMIT_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_COMMIT_TAG} to TER"
        .Build/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;
